### DISCUSSION TITLE
posts/9d0df432

### DISCUSSION THREAD

**Discussion by giscus** [fuos/fuos.github.io#1] [Announcements]
# posts/9d0df432

Hexo Theme Keep

https://fuos.github.io/posts/9d0df432.html

**Comment by fuos** [comment]
开启giscus评论！😀

**Comment by fuos** [comment]
解决GitHub actions更改更新时间的问题：[git-restore-mtime
](https://github.com/marketplace/actions/git-restore-mtime)
在GitHub actions流程中修改checkout，然后增加submodules行后面内容：
```yml
- uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
          # git-restore-mtime-bare uses the ref log to find the correct timestamp
          # for each file. This requires a full git history. The default value (1)
          # creates a shallow checkout.
          fetch-depth: 0
        # Fix timestamps
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2
```
